// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXVNehS5rDc_y7QdIyXG5C4HGXmL2nFI',
    appId: '1:23156474245:web:b28e0544ee315baefa84ec',
    messagingSenderId: '23156474245',
    projectId: 'flutterdam2',
    authDomain: 'flutterdam2.firebaseapp.com',
    storageBucket: 'flutterdam2.appspot.com',
    measurementId: 'G-7YLRB42D9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYQ-FxFThtJo2_B3FOk9GkCiYa1WFAfs',
    appId: '1:23156474245:android:450017dd5df4ebd6fa84ec',
    messagingSenderId: '23156474245',
    projectId: 'flutterdam2',
    storageBucket: 'flutterdam2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh1m3Ecv0NIxyjdl7rqU8WDqd1iG0iwFw',
    appId: '1:23156474245:ios:1c1e33f3142ddb33fa84ec',
    messagingSenderId: '23156474245',
    projectId: 'flutterdam2',
    storageBucket: 'flutterdam2.appspot.com',
    iosClientId: '23156474245-7ikq3avinj2kojgr7ki2gug88pv75dvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.metageneticsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh1m3Ecv0NIxyjdl7rqU8WDqd1iG0iwFw',
    appId: '1:23156474245:ios:8792ca3525c852d8fa84ec',
    messagingSenderId: '23156474245',
    projectId: 'flutterdam2',
    storageBucket: 'flutterdam2.appspot.com',
    iosClientId: '23156474245-tn85041ug5u2bnlete72mfl28srfp3sm.apps.googleusercontent.com',
    iosBundleId: 'com.example.metageneticsapp.RunnerTests',
  );
}
